### ISSUE TITLE
network-3.2 not allowed

### ISSUE THREAD

**Issue by ysangkok** [maoe/influxdb-haskell#100]
network-3.2 was released on hackage, but this library doesn't allow it. See:

* https://github.com/commercialhaskell/stackage/issues/7381

Note that Hackage maintainers can now [receive notifications when dependencies go out of bound](https://discourse.haskell.org/t/hackage-dep-bound-notifications-and-uploader-endorsements-for-new-users/8342?u=janus).

**Comment by maoe** [comment]
PR welcome!
