### ISSUE TITLE
InfluxDB v1.0

### ISSUE THREAD

**Issue by maoe** [maoe/influxdb-haskell#23]
- http://influxdb.com/blog/2014/12/08/clustering_tags_and_enhancements_in_0_9_0.html
- http://influxdb.com/docs/v0.8/advanced_topics/schema_design.html#migration-to-0.9.0

**Comment by sseveran** [comment]
Has there been any action on this? If not I might have time to do it.

**Comment by maoe** [comment]
I'd love to do this in a few months but I'm kind of busy at the moment. Please feel free to have a go if you like.
We probably need a design phase to do this. At a glance, we might want to drop the aeson-style (de)serialization as influxdb introduced the tagging system and it's encouraged to have only one value in a series.

Anyway, please let me know if you have any questions or even get something working.

**Comment by maoe** [comment]
I've just uploaded https://hackage.haskell.org/package/influxdb-1.0.0.
