### ISSUE TITLE
Please add support for aeson 0.9.x

### ISSUE THREAD

**Issue by peti** [maoe/influxdb-haskell#26]
Our builds of this package in NixOS [fail](http://hydra.cryp.to/build/888954/log/raw) after updating to the latest version of aeson.

**Comment by maoe** [comment]
Thanks for reporting the issue. I'll fix it in a few days.

**Comment by peti** [comment]
Ping?

**Comment by peti** [comment]
I removed influxdb from the NixOS distribution for the time being.

**Comment by maoe** [comment]
Sorry for the delay. Just released as [v0.9.1.3](https://hackage.haskell.org/package/influxdb-0.9.1.3).
