### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by beckettsean** [maoe/influxdb-haskell#31]
I'm cleaning up the https://docs.influxdata.com/influxdb/v1.0/tools/api_client_libraries/ page and removing those libraries that aren't compatible with InfluxDB 1.0. 

I'll remove this project from that page on October 15th unless you have plans to update for 1.0 compatibility. Thanks!

**Comment by maoe** [comment]
Hi Sean,

It is active. The development is going on https://github.com/maoe/influxdb-haskell/pull/30. Currently I'm experimenting this branch with our in-house applications to make the API easier to use.

**Comment by beckettsean** [comment]
Great news, @maoe. thanks! We'll keep you on the page.

**Comment by maoe** [comment]
Thank you, Sean. I'll keep this issue open until the new API is released on Hackage.

**Comment by beckettsean** [comment]
@maoe 1.1 is going live on Monday, FYI.

**Comment by maoe** [comment]
Thanks for the heads up. AFAICT from the CHANGELOG, there seems to be not much stuff I have to fix in this library.

**Comment by maoe** [comment]
I've just uploaded https://hackage.haskell.org/package/influxdb-1.0.0.
