### ISSUE TITLE
compile failure w/ base-4.7 and older

### ISSUE THREAD

**Issue by hvr** [maoe/influxdb-haskell#43]
Hi,

I noticed that the last 3 release of `influxdb` run into a compile failure (see below).

```
Configuring component lib from influxdb-1.1.1...
Preprocessing library influxdb-1.1.1...

src/Database/InfluxDB/Manage.hs:27:8:
    Could not find module ‘Data.Void’
    It is a member of the hidden package ‘void-0.7.2’.
    Perhaps you need to add ‘void’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

The easiest fix would be to tighten the lower constraint on base, i.e. `base >= 4.8` and call it a day (also because the Travis job currently only validates GHC 7.10 & GHC 8.0).

**Comment by maoe** [comment]
Oh, I didn't notice that. Thanks for reporting it. I'll make a fix.

**Comment by hvr** [comment]
@maoe Btw, I've already corrected the meta-data on the 3 affected releases:

 - https://hackage.haskell.org/package/influxdb-1.0.0/revisions
 - https://hackage.haskell.org/package/influxdb-1.1.0/revisions
 - https://hackage.haskell.org/package/influxdb-1.1.1/revisions

So there's no immediate need to upload a new release just for the meta-data.

**Comment by maoe** [comment]
Okay thanks. How did you find the issue?

**Comment by hvr** [comment]
@maoe it showed up on http://104.239.175.197:8080/package/influxdb (but it's been fixed now with the meta-data fixup)

**Comment by maoe** [comment]
Fixed in HEAD. Also thanks for the info!
