### ISSUE TITLE
FieldNull is invalid in the line protocol

### ISSUE THREAD

**Issue by maoe** [maoe/influxdb-haskell#44]
See https://github.com/influxdata/influxdb/issues/7722.

So we shouldn't be able to put `FieldNull` in `Line`.

**Comment by maoe** [comment]
FIxed in #45

**Comment by whaon** [comment]
do we can query when field is null
see the issue: #8560

**Comment by maoe** [comment]
@whaon This is an issue tracker for the Haskell client library for InfluxDB. Do you have a question that's relevant to this library?
