### ISSUE TITLE
FieldFloat to parse Int

### ISSUE THREAD

**Issue by Ulrar** [maoe/influxdb-haskell#47]
Hi,

It looks like using a FieldInt I can parse either an Int or a Float without a problem (of course for a Float it'll lose precision).
The opposite isn't true though, parsing a Double with FieldFloat (which is weirdly named ?) works, but trying to parse an Int just results in an empty Vector.

That's a bit problematic, that forces me to use Int and the loss of precision makes datas like "SELECT load1 FROM system" unusable (for a classical telegraf database). Am I missing something here ?
The goal being not to require the user to specify the field type, as that would make everything very tedious to use. If treating an Int as a Float worked, it would make everything easy to use in a generic way though.

Thanks

**Comment by maoe** [comment]
What field parser(s) are you using? It would be very helpful if you could provide a minimal reproducible code of the issue.

**Comment by Ulrar** [comment]
I'm using what's in the doc, slightly modified : 

```haskell
data Val1 = Val1
  {
    time :: UTCTime,
    value :: Double
  } deriving Show

instance QueryResults Val1 where
  parseResults prec = parseResultsWith $ \_ _ columns fields -> do
    time <- getField "time" columns fields >>= parseUTCTime prec
    FieldFloat value <- getField "value" columns fields >>= parseQueryField
    return Val1 {..}
```

**Comment by maoe** [comment]
Sorry for the late response.

I see the issue. The example code in the doc needs to be modified. Something like this should work:

```haskell
    value <- getField "value" columns fields >>= parseJSON -- from aeson
```

Perhaps `parseQueryField` needs to be abandoned or at least should have a comment about the (surprising) behavior on numeric fields.

**Comment by Ulrar** [comment]
Ah, good to know indeed. Thanks
