### ISSUE TITLE
Precision is confusing

### ISSUE THREAD

**Issue by luntain** [maoe/influxdb-haskell#63]
What is the purpose of it? Why not have only nanoseconds? This seems to be the actual representation in the database. Setting precision to anything else just loses precision. For example, setting precision to seconds now means:

* when connecting to the db, specify precision as seconds
* scale the timestamp to said precision and write on the wire
* influx db reads it, scales from seconds to nanoseconds and stores

The only effect is a loss of precision. If someone wants to lose precision on his timestamp he may well do it before passing those timestamp to the client.

**Comment by maoe** [comment]
The precision parameter is not just a loss of precision but also affects compression in the storage. It’s actually encouraged to use as coarse precision as you can. See [the official doc]( https://docs.influxdata.com/influxdb/v1.5/write_protocols/line_protocol_reference/). It says:


> Use the coarsest precision possible for timestamps. This can result in significant improvements in compression.

**Comment by luntain** [comment]
You are right. Thanks.
