### ISSUE TITLE
Support for SSL connections

### ISSUE THREAD

**Issue by skeuchel** [maoe/influxdb-haskell#70]
AFAICT ssl connections are not supported yet. Is this on the roadmap?

**Comment by maoe** [comment]
I haven't tried it myself but I think it should be possible with `http-client-tls` or `http-client-openssl`. Could you try something like this?

```haskell
tlsTest = do
  m <- newTlsManager
  let p = queryParams "test"
        & manager .~ Right m
        & server.tls .~ True
  query p ...
```

**Comment by skeuchel** [comment]
Ahh yes, that works. Thanks! I never used http-client-* directly, so I wasn't aware how to do this properly.
