### ISSUE TITLE
Backslash escaping in field values

### ISSUE THREAD

**Issue by joell** [maoe/influxdb-haskell#75]
Thank you for the wonderful work you have done on this library!  It is a joy to work with such a well-thought-out, strongly typed interface to InfluxDB.  I have run into a small escaping issue, however.

`Database.InfluxDB.Line.escapeStringField` only escapes double quotes but does not perform any type of backslash escaping.

The [InfluxDB Line Protocol documentation](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_reference/#special-characters) requires that both double quotes and backslashes be escaped (albeit the way InfluxDB handles backslashes is fairly tolerant of most cases where they are not escaped).

This leads to unexpected behavior where InfluxDB rejects certain lines.  Consider the following program:

```hs
{-# LANGUAGE OverloadedStrings #-}

import Data.Time.Clock (UTCTime)
import Database.InfluxDB
import Database.InfluxDB.Line
import qualified Data.ByteString.Lazy.Char8 as L
import qualified Data.Map as M
import qualified Data.Text.IO as T

s = "bl\\\"a"

main = do
  T.putStrLn s
  L.putStrLn $ encodeLine (scaleTo Nanosecond)
             $ Line "testing" mempty
                    (M.singleton "test" $ FieldString s)
                    (Nothing :: Maybe UTCTime)
```

When run it will output `s` verbatim follow by the library's encoding of an InfluxDB measurement line with `s` as the value of a field named "test":

```
bl\"a
testing test="bl\\"a"
```

Because the library escapes the double quote but does not escape the backslash, the result to InfluxDB's perspective is that the backslash _was_ escaped but the double quote was _not_ escaped.  If you were to feed this measurement line to InfluxDB over the HTTP interface, it yields an `unbalanced quotes` parse error.

The expected behavior would be that the library would encode the measurement line as `testing test="bl\\\"a"`, escaping both the backslash and the double quote.  This rendering InfluxDB will accept.

(This can also be an issue any time an input field string contains a literal `\\`.  InfluxDB will treat that as an escaped backslash, and so the field's double backslash becomes flattened to only a single backslash.)

**Comment by maoe** [comment]
Thanks for the detailed report and the demonstrating code. I'll make a fix probably later today.

**Comment by maoe** [comment]
Made a PR at #76. @joell Could you check if it works in your use case?

**Comment by joell** [comment]
I tested with PR #76, and it works flawlessly for my use case.  Thank you for such a rapid response!

**Comment by maoe** [comment]
Great! Thanks for checking. I’ll merge it shortly and release a new version.

**Comment by maoe** [comment]
Released https://hackage.haskell.org/package/influxdb-1.7.1.

**Comment by joell** [comment]
Thank you! :smiley:
