### ISSUE TITLE
Database Name that is Not a Literal

### ISSUE THREAD

**Issue by TitusQuinctiusFlamininus** [maoe/influxdb-haskell#77]
Hi. This is probably a simple issue to fix, but here goes: 

I would like to run this function : 

createDatabase :: String -> IO ()
createDatabase name = manage (queryParams name) $ F.formatQuery ("CREATE DATABASE "%F.database) name

The error i receive is: 
Couldn't match type ‘[Char]’ with ‘Database’
      Expected type: Database
        Actual type: String

I have the OverloadedStrings extension loaded at the top of my module

How can make the type-checker happy and manage to create databases with different names, without having to know in advance (as string literals) what they are?

**Comment by maoe** [comment]
As in the [Haddock comment for the `Database`](http://hackage.haskell.org/package/influxdb-1.7.1/docs/Database-InfluxDB.html#t:Database) type, you can construct a `Database` using `formatDatabase`.

So your snippet should be

```haskell
createDatabase :: String -> IO ()
createDatabase name =
  manage (queryParams db) $ formatQuery ("CREATE DATABASE"%F.database) db
  where
    db = formatDatabase F.string name
```

**Comment by TitusQuinctiusFlamininus** [comment]
Thank you, solved.

**Comment by telent** [comment]
I am very new to Haskell and am most likely  just parading my lack of understanding here, but in the page you link to it says 
```
>>> formatDatabase "test-db"
"test-db"
```
(i.e. it's missing the parameter `F.string`, without which it doesn't work).  Same deal with Measurement (which is actually where I became blocked on this) and Key.  I'm sure that programmers with more than a week's Haskell experience can just read the type signature, but if there's any way to address it in the docs then recently-past-me would definitely appreciate it

**Comment by maoe** [comment]
@telent Do you have -XOverloadedStrings enabled? It should just work with the extension.

That said, I agree that the examples could be improved.
