### ISSUE TITLE
UDP client writeBatch fails with too many metrics

### ISSUE THREAD

**Issue by imoverclocked** [maoe/influxdb-haskell#92]
Since the UDP client implementation of writeBatch attempts to write the entire byte stream at once, it's somewhat trivial to reproduce this error:

`Network.Socket.ByteString.sendManyTo: resource exhausted (Message too long)`

**Comment by maoe** [comment]
Yes, that's a current limitation of this library. The tracking ticket for that feature is https://github.com/maoe/influxdb-haskell/issues/61.

**Comment by imoverclocked** [comment]
I saw that one but I wasn't sure if it was exactly the same issue or not. Thank you!

**Comment by maoe** [comment]
This is something that has been implemented in the official go client library and is presumably not difficult to implement. If you're interested please don't hesitate to submit a PR. I'd be happy to review!
